actionplan:
  actionplan_text_path: "./data/actionplan/actionplan - whole.txt"
  actionplan_json_path: "./data/actionplan/actionplan.json"
  actionplan_vector_path:    "./data/vector"
app_logs:
  info_file: logs/info.log
  error_file: logs/error.log
data_exports:
  base_dir: /app/exports
  temp_dir: /tmp/exports
database:
  config_file_path: ${DB_CONFIG_PATH} # Reference an environment variable