openai:
  id: 1
  name:   "Chat GPT"
  key:    "OPENAI_KEY"
  vector: ""
  model_chat:  "gpt-4.1-mini"
  model_chat_list:
    - model1
    - model2
  model_embedding: "text-embedding-3-small"
  model_embedding_list:
    - embedding1
    - embedding2
mistral:
  id: 2
  name:   "Mistral"
  key:    "MISTRAL_KEY"
  vector: ""
  model_chat:  "magistral-small-2506"
  model_chat_list:
    - model1
    - model2
  model_embedding: "text-embedding-3-small"
  model_embedding_list:
    - embedding1
    - embedding2
deepseek:
  id: 3
  name:   "Deepseek"
  key:    "DEEPSEEK_KEY"
  vector: ""
  model_chat:  "deepseek-chat"
  model_chat_list:
    - model1
    - model2
  model_embedding: "text-embedding-3-small"
  model_embedding_list:
    - embedding1
    - embedding2
gemini:
  id: 4
  name:   "Gemini"
  key:    "GEMINI_KEY"
  vector: ""
  model_chat:  "gemini-2.0-flash"
  model_chat_list:
    - model1
    - model2
  model_embedding: "text-embedding-3-small"
  model_embedding_list:
    - embedding1
    - embedding2
claude:
  id: 5
  name:   "Claude"
  key:    "CLAUDE_KEY"
  vector: ""
  model_chat:  "gpt-4.1-mini"
  model_chat_list:
    - model1
    - model2
  model_embedding: "claude-sonnet-4-20250514"
  model_embedding_list:
    - embedding1
    - embedding2