provider_model:
  openai:
    id: 1
    name:   "Chat GPT"
    key:    "OPENAI_KEY"
    vector: ""
    model_chat:  "gpt-4.1-mini"
    model_chat_list:
      - model1
      - model2
    model_embedding: "text-embedding-3-small"
    model_embedding_list:
      - embedding1
      - embedding2
  mistral:
    id: 2
    name:   "Mistral"
    key:    "MISTRAL_KEY"
    vector: ""
    model_chat:  "magistral-small-2506"
    model_chat_list:
      - model1
      - model2
    model_embedding: "text-embedding-3-small"
    model_embedding_list:
      - embedding1
      - embedding2
  deepseek:
    id: 3
    name:   "Deepseek"
    key:    "DEEPSEEK_KEY"
    vector: ""
    model_chat:  "deepseek-chat"
    model_chat_list:
      - model1
      - model2
    model_embedding: "text-embedding-3-small"
    model_embedding_list:
      - embedding1
      - embedding2
  gemini:
    id: 4
    name:   "Gemini"
    key:    "GEMINI_KEY"
    vector: ""
    model_chat:  "gemini-2.0-flash"
    model_chat_list:
      - model1
      - model2
    model_embedding: "text-embedding-3-small"
    model_embedding_list:
      - embedding1
      - embedding2
  claude:
    id: 5
    name:   "Claude"
    key:    "CLAUDE_KEY"
    vector: ""
    model_chat:  "gpt-4.1-mini"
    model_chat_list:
      - model1
      - model2
    model_embedding: "claude-sonnet-4-20250514"
    model_embedding_list:
      - embedding1
      - embedding2

embedding_model_list:
  openai: 
    - text-embedding-3-small
    - text-embedding-3-large
  mistral:
    - mistral-embedding-1
    - mistral-embedding-2
  deepseek:
    - deepseek-embedding-1
    - deepseek-embedding-2
  gemini:
    - gemini-embedding-1
    - gemini-embedding-2
  claude:
    - claude-embedding-1
    - claude-embedding-2

##### RETRIEVER CONFIG #####
HyDE_config:
  provider: "openai"
  openai:
    model: "gpt-4.1-mini"
    temperature: 0.7
    max_tokens: 150
    prompt: |
      You are an expert content rewriter.
      Your task is to take the provided text and rewrite it to be:
      - More concise
      - Clearer and easier to understand
      - Free of jargon

      Original text:
      ---
      {patient_question}
      ---
      Rewritten text:

rewritter_config:
  openai:
    model: "gpt-4.1-mini"
    temperature: 0.7
    max_tokens: 150
    prompt: |
      You are an expert content rewriter.
      Your task is to take the provided text and rewrite it to be:
      - More concise
      - Clearer and easier to understand
      - Free of jargon

      Original text:
      ---
      {patient_question}
      ---
      Rewritten text:

dense_retriver_config: 
  search_type: "similarity"
  k: 5
  openai:
    model_embedding: "text-embedding-3-small"
    collection: "openai_text-embedding-3-small_collection"

spare_retriver_config: 
  k: 3

hydbrid_retriever_config:
  weights:
    dense: 0.6
    spare: 0.4

##### RETRIEVER CONTROLLER CONFIG #####
retriever_contrllor_config:
  retrieve_type: "hyde"


##### AGENT EXECUTOR CONFIG #####
agent_executor_config:
  provider: "openai"
  sys_prompt: | 
    Your job is to use ActionPlan text to answer questions about BRCA1 or BRCA2 or PALB2 gene fault on these categories (separated by commas) \nDeciding how to best manage your cancer risk, Accessing cancer risk management services, Worry/fear about developing cancer, Concern/fear about surgery,\nImpact of genetic risk on relationships, Connect with other women with a gene alteration,\nWorry about children/family members, Starting a family/ having more children, Menopausal symptom, Quitting smoke, Dealing with the after effects of\ndeveloping cancer. Answer question only based on given category, Gene, Min Age and Max Age.\nUse the following context to answer questions. Search your resposnes according provided 'Topic' in the context. Be as detailed as possible, but don't make up any information that's not\nfrom the context. 
    Support your resposne with some quantitative information in the context. 
    For example, if the question is about is I am at age 25 and I have BRCA1 gene fault and my question is about  Worry/fear about developing cancer, Concern/fear about surgery  \nthen the supportive qualitative information will be 'The average risk of developing breast cancer between 25-30 years if you have a BRCA1 gene fault is around 2-7%'.  
    \nSupport your answer by always including some useful references. 
    Such references are available after the keyword 'Heading: Resources' or 'Heading: Resources which you may find helpful' or 'Heading: Evidence' in the context'. 
    \nIf there is single word in Question such as 'hello' or 'test' tell to write appropiate question in detail.\nNever say 'I am an AI assistant' in your response. If you don't know an answer, say Sorry I don't have any information to answer your question,\nA Genetic Counselor will contact you to provide a response.\n\n{context} 
  tool_desc_action_plan: "Useful when you need to answer questions.Search your resposnes according provided 'Topic' in the context. Be as detailed as possible, but don't make up any information that's notfrom the context. Support your resposne with some quantitative information in the context. For example, if the question is about is I am at age 25 and I have BRCA1 gene fault and my question is about  Worry/fear about developing cancer, Concern/fear about surgery then the supportive qualitative information will be 'The average risk of developing breast cancer between 25-30 years if you have a BRCA1 gene fault is around 2-7%'.  Support your answer by always including some useful references. Such references are available after the keyword 'Heading: Resources' or 'Heading: Resources which you may find helpful' or 'Heading: Evidence' in the context'.If there is single word in Question such as 'hello' or 'test' tell to write appropiate question in detail.Never say 'I am an AI assistant' in your response"
  vector_k: 3
  openai:
    model: "gpt-4.1-mini"
    model_embedding: "text-embedding-3-small"
    temperature: 0.7
    max_tokens: 150
    prompt: ""


   